apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-frontend
  template:
    metadata:
      labels:
        app: capstone-frontend
    spec:
      containers:
        - name: capstone-frontend
          image: thong19981110vn/capstone-frontend:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
      restartPolicy: Always